version: '3.8'

services:
  # Aplicação completa (frontend + backend)
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sistema-financas
    environment:
      # Variáveis do backend
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      PORT: 3001
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "80:80"  # Nginx serve tudo na porta 80
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
