version: '3.8'

services:
  # Aplicação completa (frontend + backend em um único container)
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sistema-financas
    environment:
      # Variáveis do backend
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      BACKEND_PORT: 3001
      PORT: 3001
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      # Variáveis do frontend (já definidas no build)
      VITE_API_URL: ${VITE_API_URL:-/api}
    ports:
      # IMPORTANTE: Coolify espera a aplicação na porta 3000
      - "3000:3000"  # Nginx serve tudo na porta 3000
    restart: unless-stopped
    healthcheck:
      # Health check simplificado que verifica o endpoint do nginx
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - coolify
    # Limites de recursos para evitar problemas de memória
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

networks:
  coolify:
    external: true
