services:
  # Aplicação principal (frontend + backend)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financas-app
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3001}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_API_URL: ${VITE_API_URL:-/api}
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - app_logs:/app/logs
    networks:
      - financas-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  app_logs:
    driver: local

networks:
  financas-network:
    driver: bridge