version: '3.8'

services:
  app:
    image: es4ckok8g0k0sgo0w0o044kk:${SOURCE_COMMIT:-latest}
    container_name: es4ckok8g0k0sgo0w0o044kk-${COOLIFY_CONTAINER_NAME:-local}
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
      - FRONTEND_URL=${FRONTEND_URL}
      - VITE_API_URL=/api
    ports:
      - "80:80"
    networks:
      - coolify
    # healthcheck removido temporariamente para evitar erro de template parsing
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/health", "||", "exit", "1"]
    #   interval: 30s
    #   timeout: 15s
    #   retries: 5
    #   start_period: 90s

networks:
  coolify:
    external: true