version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - FINANCAS_POSTGRES_DB=${FINANCAS_POSTGRES_DB}
      - FINANCAS_POSTGRES_USER=${FINANCAS_POSTGRES_USER}
      - FINANCAS_POSTGRES_PASSWORD=${FINANCAS_POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped